In [4]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from tqdm import tqdm
import os
import shutil

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [50]:
directory = '/content/drive/MyDrive/'
images_dir = directory + 'generated'
original_dir = directory + 'anime_original'

In [5]:
img_path=os.listdir(images_dir)


In [6]:
print(img_path)

['generated-images-000_e1.png', 'generated-images-001_e0.png', 'generated-images-002_e0.png', 'generated-images-003_e0.png', 'generated-images-004_e0.png', 'generated-images-005_e0.png', 'generated-images-006_e0.png', 'generated-images-007_e0.png', 'generated-images-008_e0.png', 'generated-images-009_e0.png', 'generated-images-010_e0.png', 'generated-images-011_e0.png', 'generated-images-012_e0.png', 'generated-images-013_e0.png', 'generated-images-014_e0.png', 'generated-images-015_e0.png', 'generated-images-016_e0.png', 'generated-images-001_e1.png', 'generated-images-002_e1.png', 'generated-images-003_e1.png', 'generated-images-004_e1.png', 'generated-images-005_e1.png', 'generated-images-006_e1.png', 'generated-images-007_e1.png', 'generated-images-008_e1.png', 'generated-images-009_e1.png', 'generated-images-010_e1.png', 'generated-images-011_e1.png', 'generated-images-012_e1.png', 'generated-images-013_e1.png', 'generated-images-014_e1.png', 'generated-images-015_e1.png', 'genera

# Initially was using 2 folders (original/generated), then merged in 1, thus section Merged

In [22]:
images_to_cluster = []
for img in img_path:
  if '_e5' in img or '_e10' in img or '_e20' in img or '_e39' in img:
    images_to_cluster.append(img)

print(images_to_cluster)

['generated-images-001_e5.png', 'generated-images-002_e5.png', 'generated-images-003_e5.png', 'generated-images-004_e5.png', 'generated-images-005_e5.png', 'generated-images-006_e5.png', 'generated-images-007_e5.png', 'generated-images-008_e5.png', 'generated-images-009_e5.png', 'generated-images-010_e5.png', 'generated-images-011_e5.png', 'generated-images-012_e5.png', 'generated-images-013_e5.png', 'generated-images-014_e5.png', 'generated-images-015_e5.png', 'generated-images-016_e5.png', 'generated-images-001_e10.png', 'generated-images-002_e10.png', 'generated-images-003_e10.png', 'generated-images-004_e10.png', 'generated-images-005_e10.png', 'generated-images-006_e10.png', 'generated-images-007_e10.png', 'generated-images-008_e10.png', 'generated-images-009_e10.png', 'generated-images-010_e10.png', 'generated-images-011_e10.png', 'generated-images-012_e10.png', 'generated-images-013_e10.png', 'generated-images-014_e10.png', 'generated-images-015_e10.png', 'generated-images-016_e

In [52]:
original_img_path=os.listdir(original_dir)
print(original_img_path)

['image_0.jpg', 'image_2.jpg', 'image_1.jpg', 'image_5.jpg', 'image_3.jpg', 'image_4.jpg', 'image_6.jpg', 'image_7.jpg', 'image_8.jpg', 'image_9.jpg', 'image_10.jpg', 'image_11.jpg', 'image_12.jpg', 'image_13.jpg', 'image_15.jpg', 'image_14.jpg']


In [58]:
merged_images = []
merged_images.append(images_to_cluster)
merged_images.append(original_img_path)
merged_images = sum(merged_images, []) #flattens the array
print(merged_images)

['generated-images-001_e5.png', 'generated-images-002_e5.png', 'generated-images-003_e5.png', 'generated-images-004_e5.png', 'generated-images-005_e5.png', 'generated-images-006_e5.png', 'generated-images-007_e5.png', 'generated-images-008_e5.png', 'generated-images-009_e5.png', 'generated-images-010_e5.png', 'generated-images-011_e5.png', 'generated-images-012_e5.png', 'generated-images-013_e5.png', 'generated-images-014_e5.png', 'generated-images-015_e5.png', 'generated-images-016_e5.png', 'generated-images-001_e10.png', 'generated-images-002_e10.png', 'generated-images-003_e10.png', 'generated-images-004_e10.png', 'generated-images-005_e10.png', 'generated-images-006_e10.png', 'generated-images-007_e10.png', 'generated-images-008_e10.png', 'generated-images-009_e10.png', 'generated-images-010_e10.png', 'generated-images-011_e10.png', 'generated-images-012_e10.png', 'generated-images-013_e10.png', 'generated-images-014_e10.png', 'generated-images-015_e10.png', 'generated-images-016_e

In [61]:
image_cluster = pd.DataFrame(merged_images, columns=['image'])
image_cluster

image
0   generated-images-001_e5.png
1   generated-images-002_e5.png
2   generated-images-003_e5.png
3   generated-images-004_e5.png
4   generated-images-005_e5.png
..                          ...
75                 image_11.jpg
76                 image_12.jpg
77                 image_13.jpg
78                 image_15.jpg
79                 image_14.jpg

[80 rows x 1 columns]

In [101]:
labels = []

for img in images_to_cluster:
  if '_e5' in img:
    labels.append(1)
  elif '_e10' in img:
    labels.append(2)
  elif '_e20' in img:
    labels.append(3)
  elif '_e39' in img:
    labels.append(4)

for img in original_img_path:
  labels.append(5)

In [102]:
print(labels)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [75]:
print(len(labels))

80


In [76]:
image_cluster["clusterid"] = labels
image_cluster

image  clusterid
0   generated-images-001_e5.png          1
1   generated-images-002_e5.png          1
2   generated-images-003_e5.png          1
3   generated-images-004_e5.png          1
4   generated-images-005_e5.png          1
..                          ...        ...
75                 image_11.jpg          5
76                 image_12.jpg          5
77                 image_13.jpg          5
78                 image_15.jpg          5
79                 image_14.jpg          5

[80 rows x 2 columns]

# Merging files 

In [84]:
# original_dir
merged_dir = directory + '/merged_animes'
anime_dir = directory + 'anime_original2'

# for img in os.listdir(anime_dir):
#   newPath = shutil.copy(anime_dir+'/'+img, merged_dir+'/'+img)

In [93]:
merged_dir_path=os.listdir(merged_dir)
print(merged_dir_path)

['image_14.jpg', 'image_0.jpg', 'image_1.jpg', 'image_2.jpg', 'image_3.jpg', 'image_4.jpg', 'image_5.jpg', 'image_6.jpg', 'image_7.jpg', 'image_8.jpg', 'image_9.jpg', 'image_10.jpg', 'image_11.jpg', 'image_12.jpg', 'image_13.jpg', 'image_15.jpg', 'generated-images-000_e1.png', 'generated-images-001_e0.png', 'generated-images-002_e0.png', 'generated-images-003_e0.png', 'generated-images-004_e0.png', 'generated-images-005_e0.png', 'generated-images-006_e0.png', 'generated-images-007_e0.png', 'generated-images-008_e0.png', 'generated-images-009_e0.png', 'generated-images-010_e0.png', 'generated-images-011_e0.png', 'generated-images-012_e0.png', 'generated-images-013_e0.png', 'generated-images-014_e0.png', 'generated-images-015_e0.png', 'generated-images-016_e0.png', 'generated-images-001_e1.png', 'generated-images-002_e1.png', 'generated-images-003_e1.png', 'generated-images-004_e1.png', 'generated-images-005_e1.png', 'generated-images-006_e1.png', 'generated-images-007_e1.png', 'generate

In [88]:
# for img in os.listdir(images_dir):
#   newPath = shutil.copy(images_dir+'/'+img, merged_dir+'/'+img)

In [94]:
merged_images_to_cluster = []
for img in merged_dir_path:
  if '_e5' in img or '_e10' in img or '_e20' in img or '_e39' in img or 'image_' in img:
    merged_images_to_cluster.append(img)

print(merged_images_to_cluster)

['image_14.jpg', 'image_0.jpg', 'image_1.jpg', 'image_2.jpg', 'image_3.jpg', 'image_4.jpg', 'image_5.jpg', 'image_6.jpg', 'image_7.jpg', 'image_8.jpg', 'image_9.jpg', 'image_10.jpg', 'image_11.jpg', 'image_12.jpg', 'image_13.jpg', 'image_15.jpg', 'generated-images-001_e5.png', 'generated-images-002_e5.png', 'generated-images-003_e5.png', 'generated-images-004_e5.png', 'generated-images-005_e5.png', 'generated-images-006_e5.png', 'generated-images-007_e5.png', 'generated-images-008_e5.png', 'generated-images-009_e5.png', 'generated-images-010_e5.png', 'generated-images-011_e5.png', 'generated-images-012_e5.png', 'generated-images-013_e5.png', 'generated-images-014_e5.png', 'generated-images-015_e5.png', 'generated-images-016_e5.png', 'generated-images-001_e10.png', 'generated-images-002_e10.png', 'generated-images-003_e10.png', 'generated-images-004_e10.png', 'generated-images-005_e10.png', 'generated-images-006_e10.png', 'generated-images-007_e10.png', 'generated-images-008_e10.png', '

In [155]:
image_cluster_merged = pd.DataFrame(merged_images_to_cluster, columns=['image'])
image_cluster_merged

image
0                   image_14.jpg
1                    image_0.jpg
2                    image_1.jpg
3                    image_2.jpg
4                    image_3.jpg
..                           ...
75  generated-images-012_e39.png
76  generated-images-013_e39.png
77  generated-images-014_e39.png
78  generated-images-015_e39.png
79  generated-images-016_e39.png

[80 rows x 1 columns]

In [150]:
merged_labels = []
for img in merged_images_to_cluster:
  if '_e5' in img:
    merged_labels.append(0)
  elif '_e10' in img:
    merged_labels.append(1)
  elif '_e20' in img:
    merged_labels.append(2)
  elif '_e39' in img:
    merged_labels.append(3)
  else:
    merged_labels.append(4)  

In [151]:
print(merged_labels)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [156]:
image_cluster_merged["clusterid"] = merged_labels
image_cluster_merged

image  clusterid
0                   image_14.jpg          4
1                    image_0.jpg          4
2                    image_1.jpg          4
3                    image_2.jpg          4
4                    image_3.jpg          4
..                           ...        ...
75  generated-images-012_e39.png          3
76  generated-images-013_e39.png          3
77  generated-images-014_e39.png          3
78  generated-images-015_e39.png          3
79  generated-images-016_e39.png          3

[80 rows x 2 columns]

# **K-Means**

# Inception

In [27]:
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input

In [110]:
def image_feature_merged():
    model = InceptionV3(weights='imagenet', include_top=False)
    features = [];
    img_name = [];
    for i in tqdm(merged_images_to_cluster):
        fname= merged_dir + '/' + i
        img=image.load_img(fname,target_size=(224,224))
        x = img_to_array(img)
        x=np.expand_dims(x,axis=0)
        x=preprocess_input(x)
        feat=model.predict(x)
        feat=feat.flatten()
        features.append(feat)
        img_name.append(i)
    return features,img_name

In [111]:
img_features_merged, img_name_merged = image_feature_merged()

100%|██████████| 80/80 [00:14<00:00,  5.54it/s]


In [112]:
k = 5
clusters2 = KMeans(k, random_state = 40)
clusters2.fit(img_features_merged)

KMeans(n_clusters=5, random_state=40)

In [157]:
image_cluster_merged["Inception_predicted_clusterid"] = clusters2.labels_ 
image_cluster_merged

image  clusterid  Inception_predicted_clusterid
0                   image_14.jpg          4                              2
1                    image_0.jpg          4                              1
2                    image_1.jpg          4                              2
3                    image_2.jpg          4                              2
4                    image_3.jpg          4                              2
..                           ...        ...                            ...
75  generated-images-012_e39.png          3                              1
76  generated-images-013_e39.png          3                              1
77  generated-images-014_e39.png          3                              1
78  generated-images-015_e39.png          3                              1
79  generated-images-016_e39.png          3                              1

[80 rows x 3 columns]

# VGG net

In [79]:
import keras
from keras.applications.vgg16 import VGG16
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D, Dropout, UpSampling2D, Conv2D, MaxPooling2D, Activation, Flatten

base_model = VGG16(weights='imagenet', input_shape=(224,224,3), include_top=False)
base_out = base_model.output
flt = Flatten()(base_out)
dns = Dense(units=100, activation='sigmoid')(flt) 
vgg_model = Model(base_model.input, dns)

In [114]:
def vgg_image_feature():
    features = [];
    img_name = [];
    for i in tqdm(merged_images_to_cluster):
        fname= merged_dir + '/' + i
        img=image.load_img(fname,target_size=(224,224))
        x = img_to_array(img)
        x=np.expand_dims(x,axis=0)
        x=preprocess_input(x)
        feat=model.predict(x)
        feat=feat.flatten()
        features.append(feat)
        img_name.append(i)
    return features,img_name

In [115]:
img_features_VGG, img_name_VGG = vgg_image_feature()

100%|██████████| 80/80 [00:40<00:00,  1.95it/s]


In [146]:
k = 5
clusters_vgg = KMeans(k, random_state = 40)
clusters_vgg.fit(img_features_VGG)

KMeans(n_clusters=5, random_state=40)

In [158]:
image_cluster_merged["VGG_predicted_clusterid"] = clusters_vgg.labels_ 
image_cluster_merged

image  ...  VGG_predicted_clusterid
0                   image_14.jpg  ...                        2
1                    image_0.jpg  ...                        2
2                    image_1.jpg  ...                        2
3                    image_2.jpg  ...                        2
4                    image_3.jpg  ...                        2
..                           ...  ...                      ...
75  generated-images-012_e39.png  ...                        1
76  generated-images-013_e39.png  ...                        4
77  generated-images-014_e39.png  ...                        4
78  generated-images-015_e39.png  ...                        3
79  generated-images-016_e39.png  ...                        1

[80 rows x 4 columns]

# **Evaluation**

In [ ]:
for i in range(10):
    print('Accuracy of %5s : %2d %%' % (
        classes[i], 100 * class_correct[i] / class_total[i]))

In [161]:
count = 0
originalIds = image_cluster_merged["clusterid"].tolist()
predictedIds = image_cluster_merged["VGG_predicted_clusterid"].tolist()

intersections = [i for i, j in zip(originalIds, predictedIds) if i == j]
accuracy = 100*len(intersections)/80
print("accuracy = ",accuracy)

accuracy =  25.0


In [136]:
print(originalIds)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [160]:
print(predictedIds)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 3, 4, 4, 3, 0, 4, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 3, 4, 4, 3, 1, 1, 1, 1, 1, 3, 1, 4, 4, 3, 1]


In [163]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [164]:
print(classification_report(originalIds, predictedIds))

              precision    recall  f1-score   support

           0       0.53      1.00      0.70        16
           1       0.00      0.00      0.00        16
           2       0.00      0.00      0.00        16
           3       0.36      0.25      0.30        16
           4       0.00      0.00      0.00        16

    accuracy                           0.25        80
   macro avg       0.18      0.25      0.20        80
weighted avg       0.18      0.25      0.20        80



In [165]:
print(confusion_matrix(originalIds, predictedIds))

[[16  0  0  0  0]
 [13  0  0  3  0]
 [ 1  8  0  4  3]
 [ 0  8  0  4  4]
 [ 0  0 16  0  0]]
